LEDGER_GROUPS = {
	purchase_accounts: 'Purchase Accounts',
	sales_accounts: 'Sales Account',
	duties_and_taxes: 'Duties and Taxes',
	direct_expenses: 'Direct Expenses OR Expenses(Direct)',
	indirect_expenses: 'Indirect Expenses OR Expense(Indirect)',
	indirect_income: 'Indirect Income OR Income(Indirect)',
	cash_ledgers: 'Cash',
	profit_and_loss_accounts: 'Profit and Loss Account',
	bank_account: 'Bank Account',
	deposit_account: 'Deposit Account',
	capital_account: 'Capital A/c',
	current_assets: 'Current Assets',
	current_liabilities: 'Current Liabilities',
	loan_and_advances: 'Loans and Advances (Assets)',
	loans_liabilities: 'Loans Liabilities',
	fixed_assets: 'Fixed Assets',
	bank_occ: 'Bank OCC',
	bank_od: 'Bank OD',
	branch_divisions: 'Branch/Divisions',
	cash_in_hand: 'Cash in Hand',
	investments: 'Investments',
	stock_in_hand: 'Stock-in-hand',
	misc_expenses: 'Misc. Expense (ASSET)',
	suspense_ac: 'Suspense A/c',
	secured_loan: 'Secured Loan',
	unsecured_loan: 'Unsecured Loan',
	reserve_and_surplus: 'Reserve & Surplus',
	provisions: 'Provisions',
	retained_earring: 'Retained Earring',
	direct_income: 'Direct Incomes OR Income(Direct)'
}